views.py
import os
from random import shuffle

from flask import redirect, url_for, flash, render_template, Blueprint, request, json, current_app
from flask_login import login_required, current_user, login_user, logout_user
from sqlalchemy import func, and_
from werkzeug.utils import secure_filename

from config import STATIC_FOLDER, IMAGES_FOLDER
from models import User, db, Question, QuizScore, Quiz, Answer, Image
from forms import LoginForm, RegistrationForm, AddQuestionForm, SelectQuizForm, EditQuizForm
from datetime import datetime, timezone
import plotly.express as px

views_app = Blueprint('views', __name__)
admin_app = Blueprint('admin', __name__)


# username:user, pass:user
# username:admin, pass:admin


# Ako je korisnik prijavljen, preusmjerava na 'views.welcome', inače na 'views.login'.
@views_app.route('/')
def root():
    if current_user.is_authenticated:
        if current_user.is_admin:
            return redirect(url_for('admin.select_quiz'))
        else:
            return redirect(url_for('views.welcome'))
    else:
        return redirect(url_for('views.login'))


# Prikazuje obrazac za prijavu i obrađuje prijavu korisnika
@views_app.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()

        if user and user.check_password(form.password.data):
            login_user(user)
            flash('Login successful!', 'success')

            next_page = request.args.get('next')
            if current_user.is_admin:
                return redirect(next_page or url_for('admin.admin_dashboard'))
            else:
                return redirect(next_page or url_for('views.welcome'))

        else:
            # Dodaj grešku na polja username i password
            form.username.errors.append('Netočno korisničko ime ili lozinka.')
            form.password.errors.append('Netočno korisničko ime ili lozinka.')

    return render_template('login.html', form=form)


# Prikazuje obrazac za registraciju i obrađuje registraciju novog korisnika
@views_app.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        # Provjeri postoji li već user s tim usernameom
        existing_user = User.query.filter_by(username=form.username.data).first()
        if existing_user:
            # Greška ako user s tim usernameom već postoji
            form.username.errors.append('Korisničko ime već postoji. Molimo odaberite drugo.')
            return redirect(url_for('views.register'))

        # Kreiranje novog usera
        new_user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            username=form.username.data
        )
        new_user.set_password(form.password.data)

        # Spremi novog usera u bazu
        db.session.add(new_user)
        db.session.commit()

        flash('Registration successful! You can now log in.', 'success')
        return redirect(url_for('views.login'))

    return render_template('register.html', form=form)


# Prikazuje i obrađuje kviz za zadani ID kviza
@views_app.route('/quiz/<int:quiz_id>', methods=['GET', 'POST'])
@login_required
def quiz(quiz_id):
    questions = Question.query.filter_by(quiz_id=quiz_id).all()
    quiz_name = Quiz.query.get(quiz_id).quiz_name

    for question in questions:
        shuffle(question.answers)

    if request.method == 'POST':
        user_answers_json = request.form.get('userAnswers')

        if user_answers_json:
            user_answers = json.loads(user_answers_json)
        else:
            user_answers = {}

        correct_count = 0  # Broj točnih odgovora
        total_questions = len(questions)

        for question in questions:
            question_id = str(question.id)
            user_answer = user_answers.get(question_id)

            correct_answer = next((answer for answer in question.answers if answer.is_correct), None)
            if user_answer and correct_answer:
                if user_answer == correct_answer.option_text:
                    correct_count += 1

        # Izračunaj postotak
        if total_questions > 0:
            percentage_score = round((correct_count / total_questions) * 100)
        else:
            percentage_score = 0

        # Spremi rezultat u bazu
        quiz_score = QuizScore(user_id=current_user.id, quiz_id=quiz_id, score=percentage_score,
                               date=datetime.now(timezone.utc))
        db.session.add(quiz_score)
        db.session.commit()

        return render_template('quiz1.html', quiz_id=quiz_id, quiz_name=quiz_name, score=percentage_score, total=100)

    shuffle(questions)

    return render_template('quiz1.html', quiz_id=quiz_id, quiz_name=quiz_name, questions=questions, score=None)


# Prikazuje rang listu za određeni kviz s najboljim rezultatom za svakog korisnika
@views_app.route('/highscores/<int:quiz_id>')
@login_required
def highscores(quiz_id):
    # Nađi najbolji rezultat po useru
    high_scores = db.session.query(
        User.username,
        func.max(QuizScore.score).label('max_score'),
        func.max(QuizScore.date).label('max_date')
    ).join(QuizScore, User.id == QuizScore.user_id). \
        filter(QuizScore.quiz_id == quiz_id). \
        group_by(User.username). \
        order_by(func.max(QuizScore.score).desc()).limit(10).all()

    return render_template('highscores.html', quiz_id=quiz_id, high_scores=high_scores)


# prikaz profila s rezultatima
@views_app.route('/profile')
@login_required
def profile():
    user_highscores = (
        db.session.query(Quiz.quiz_name, db.func.max(QuizScore.score).label('max_score'))
        .join(QuizScore, Quiz.id == QuizScore.quiz_id)
        .filter_by(user_id=current_user.id)
        .group_by(Quiz.quiz_name)
        .all()
    )

    return render_template('profile.html', user_highscores=user_highscores, username=current_user.username)


@views_app.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('views.login'))


# početna stranica, prikazuje sve kvizove
@views_app.route('/welcome')
@login_required
def welcome():
    quizzes = Quiz.query.all()

    return render_template('welcome.html', username=current_user.username, quizzes=quizzes)


# početna stranica za admina
@admin_app.route('/admin', methods=['GET'])
@login_required
def admin_dashboard():
    if current_user.is_admin:  # provjera je li user admin
        return redirect(url_for('admin.select_quiz'))
    else:
        return redirect(
            url_for('views.welcome'))  # ako pokušava pristupiti ne admin redirect na njegovu početnu stranicu


# selektiranje kviza za kojeg će se mijenjati/dodavati pitanja
@admin_app.route('/select_quiz', methods=['GET', 'POST'])
@login_required
def select_quiz():
    quizzes = Quiz.query.all()

    if current_user.is_admin:
        form = SelectQuizForm()
        form.quiz.choices = [(quiz_el.id, quiz_el.quiz_name) for quiz_el in quizzes]

        if form.validate_on_submit():
            selected_quiz_id = int(request.form.get('quiz'))
            return redirect(url_for('admin.list_questions', quiz_id=selected_quiz_id))

        return render_template('admin/selectQuiz.html', form=form, quizzes=quizzes)
    else:
        return redirect(url_for('views.welcome'))


# Dodavanje novog kviza
@admin_app.route('/add_quiz', methods=['POST'])
@login_required
def add_quiz():
    if current_user.is_admin:
        if request.method == 'POST':
            new_quiz_name = request.form.get('new_quiz')

            if new_quiz_name:
                new_quiz = Quiz(quiz_name=new_quiz_name)
                db.session.add(new_quiz)
                db.session.commit()

        return redirect(url_for('admin.select_quiz'))
    else:
        return redirect(url_for('views.welcome'))


# Brisanje kviza
@admin_app.route('/delete_quiz/<int:quiz_id>', methods=['GET', 'POST'])
@login_required
def delete_quiz(quiz_id):
    if current_user.is_admin:
        quiz_to_delete = Quiz.query.get_or_404(quiz_id)

        for question in quiz_to_delete.questions:
            db.session.delete(question)

        db.session.delete(quiz_to_delete)
        db.session.commit()

        return redirect(url_for('admin.select_quiz'))
    else:
        return redirect(url_for('views.welcome'))


# popis pitanja, mogućnost brisanja ili izmjene pojedinih pitanja u određenom kvizu
@admin_app.route('/list_questions/<int:quiz_id>', methods=['GET', 'POST'])
@login_required
def list_questions(quiz_id):
    questions = Question.query.filter_by(quiz_id=quiz_id).all()
    selected_quiz = Quiz.query.get(quiz_id)
    edit_quiz_form = EditQuizForm()

    if edit_quiz_form.validate_on_submit():
        new_quiz_name = edit_quiz_form.new_quiz_name.data
        selected_quiz.quiz_name = new_quiz_name
        db.session.commit()
        return redirect(url_for('admin.list_questions', quiz_id=quiz_id))

    edit_quiz_form.new_quiz_name.data = selected_quiz.quiz_name
    return render_template('admin/listQuestions.html', quiz_id=quiz_id, quiz_name=selected_quiz.quiz_name,
                           questions=questions, edit_quiz_form=edit_quiz_form)


# dodavanje pitanja u kviz
@admin_app.route('/add_question/<int:quiz_id>', methods=['GET', 'POST'])
@login_required
def add_question(quiz_id):
    if current_user.is_admin:
        form = AddQuestionForm()

        if form.validate_on_submit():
            question_text = form.question_text.data
            options = [
                form.option_a.data,
                form.option_b.data,
                form.option_c.data,
                form.option_d.data
            ]
            correct_option = form.correct_option.data

            # Kreiranje pitanja i dodavanje u bazu
            new_question = Question(
                quiz_id=quiz_id,
                question_text=question_text

templates/footer.html
<footer class="footer fixed-bottom bg-dark text-light">
    <div class="container d-flex align-items-center justify-content-center" style="padding-top: 10px;">
        <p>&copy; 2024 QuizApp</p>
    </div>
</footer>

templates/highscores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rang lista</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles-quiz.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"  />

</head>
<body>
{% include 'navbar.html' %}

<div class="container mt-4">
    <h1 class="quiz-title">Rang lista</h1>

    <!-- Tablica za prikaz rang liste -->
    <table class="table table-bordered table-hover mt-3">
        <thead class="thead-dark">
        <tr>
            <th scope="col">Mjesto</th>
            <th scope="col">Rezultat</th>
            <th scope="col">Vatrogasac</th>
        </tr>
        </thead>
        <tbody>
        {% for high_score in high_scores %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ high_score.max_score }}</td>
                <td>{{ high_score.username }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="float-right mt-3" id="backBtn">
        <a href="{{ url_for('views.quiz', quiz_id=quiz_id) }}" class="btn btn-dark">Vrati se na kviz</a>
    </div>
</div>


{% include 'footer.html' %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prijava</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles-quiz.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"  />

</head>
<body>

{% include 'navbar.html' %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    <h3 class="mb-0">Prijava</h3>
                </div>
                <div class="card-body">
                    <!-- Početak forme -->
                    <form method="POST" action="{{ url_for('views.login') }}">
                        {{ form.csrf_token }}
                        <div class="form-group">
                            <label for="username" class="font-weight-bold">Korisničko ime:</label>
                            <input type="text" class="form-control {% if form.username.errors %}is-invalid{% endif %}" id="username" name="username" required>
                            {% for error in form.username.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="password" class="font-weight-bold">Lozinka:</label>
                            <input type="password" class="form-control {% if form.password.errors %}is-invalid{% endif %}" id="password" name="password" required>
                            {% for error in form.password.errors %}
                                <div class="invalid-feedback">{{ error }}</div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-dark btn-block">Prijava</button>
                    </form>
                    <!-- Kraj forme -->
                </div>
                <div class="card-footer text-center">
                    <p class="mb-0">Nemaš korisnički račun? <a href="{{ url_for('views.register') }}">Registriraj se</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'footer.html' %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{{ url_for('views.root') }}">
            <i class="fas fa-fire fire-icon" style="color: red;"></i>
            <span class="app-logo">FirefighterQuiz</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if current_user.is_admin %}
                    <!-- Prikaz admin dijela samo adminu -->
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.admin_dashboard') }}">Admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.quiz_statistics_all') }}">Statistika kvizova</a>
                    </li>
                {% endif %}
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.welcome') }}">Kvizovi</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.profile') }}">Profil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('views.logout') }}">Odjava</a>
                    </li>

                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/quiz1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ quiz_name }}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles-quiz.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"  />

    <style>
        .question-container {
            display: none;
        }

        #backBtn {
            display: none;
        }
    </style>
</head>
<body>

{% include 'navbar.html' %}

<div class="container mt-3 col-lg-6 col-md-8 col-11">
    <h1 class="quiz-title text-dark">{{ quiz_name }}</h1>

    {% if score is none %}

        <div class=" text-center">
            <div>
                <button class="mt-5 btn btn-primary btn-lg" id="startQuizBtn">START</button>
            </div>
            <div>
                <button class="btn btn-warning btn-lg mt-3" id="startPracticeBtn">Želim vježbati</button>
            </div>

            <div>
                <a id="highscoresBtn" href="{{ url_for('views.highscores', quiz_id=quiz_id) }}" class=" mt-5 btn btn-success mt-3">Rang lista</a>
            </div>
        </div>
        <div class="col">
            <!-- Prikaz timera -->
            <div id="timerDisplay" class="text-right"></div>
        </div>

        <form method="POST" action="{{ url_for('views.quiz', quiz_id=quiz_id) }}" id="quizForm">

            {% for question in questions %}

                <div class="question-container" id="question{{ question.id }}">

                    <div class="card quiz-card">
                        <div class="card-body">
                            <h5 class="card-title">{{ question.question_text }}</h5>

                            {% if question.image %}
                                <img src="{{ url_for('static', filename=question.image.file_path) }}" alt="Question Image" style="height: 100px; margin: 10px 0 20px 0;">
                            {% endif %}

                            <div class="list-group">
                                {% for answer in question.answers %}
                                    <button class="list-group-item list-group-item-action answer-button" type="button" data-answer="{{ answer.option_text }}">
                                        {{ answer.option_text }}
                                    </button>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}

            <input type="hidden" name="userAnswers" id="userAnswers" value="">
        </form>
    {% endif %}

    <!-- Prikaz rezultata ako postoji-->
    {% if score is not none %}
        <div class="mt-3 text-center">
            <h3 class="mt-3" style="color: #dc3545;">Rezultat: {{ score }}/{{ total }}</h3>
            <!-- Gumb za prikaz rang liste -->
            <a href="{{ url_for('views.highscores', quiz_id=quiz_id) }}" class="mt-3 btn btn-success">Rang lista</a>
        </div>

    {% endif %}
    <div class="float-right mt-2" id="backBtn">
        <a href="{{ url_for('views.quiz', quiz_id=quiz_id) }}" class="btn btn-dark">Vrati se na kviz</a>
    </div>
    <div class="mt-5 text-center" id="welcomeBtn">
        <a href="{{ url_for('views.welcome') }}" class="btn btn-dark">Svi kvizovi</a>
    </div>

</div>


{% include 'footer.html' %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.7/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>


<script>

    document.addEventListener('DOMContentLoaded', function () {
        const questionContainers = document.querySelectorAll('.question-container');
        let currentQuestion = 0;
        const answeredQuestions = {};
        let timed = false;
        // Varijable za timer
        let questionTimer; // Timer za svako pitanje
        const questionTimeout = 10000; // 10s po pitanju

        const timerDisplay = document.getElementById('timerDisplay');

        // Base font sizes for different screen widths
        const fontSizeConfig = {
            large: {
                maxFontSize: 1.5,
                minFontSize: 1,
                maxLength: 100
            },
            medium: {
                maxFontSize: 1.2,
                minFontSize: 0.9,
                maxLength: 80
            },
            small: {
                maxFontSize: 1,
                minFontSize: 0.8,
                maxLength: 60
            }
        };

        // Get font size configuration based on screen width
        function getFontSizeConfig() {
            if (window.innerWidth <= 576) {
                return fontSizeConfig.small;
            } else if (window.innerWidth <= 768) {
                return fontSizeConfig.medium;
            } else {
                return fontSizeConfig.large;
            }
        }


        // prikaz pitanja
        function showQuestion() {
            // Ako se kliknulo na start pokreni timer
            if(timed === true) {
                startQuestionTimer();
            }

            if (currentQuestion < questionContainers.length) {
                adjustFontSize(questionContainers[currentQuestion]);
                questionContainers[currentQuestion].style.display = 'block';
                timerDisplay.style.display = 'block';
            }
        }

        // Event listeneri
        document.getElementById('startQuizBtn').addEventListener('click', function () {
            document.getElementById('startQuizBtn').style.display = 'none'; // Hide the button
            document.getElementById('startPracticeBtn').style.display = 'none'; // Hide the button
            document.getElementById('highscoresBtn').style.display = 'none'; // Hide the button
            document.getElementById('timerDisplay').style.display = 'block'; // Display time
            document.getElementById('backBtn').style.display = 'block'; // Display time
            document.getElementById('welcomeBtn').style.display = 'none'; // Display time

            // Ako je start onda promijeni varijablu tako da se mjeri vrijeme
            timed = true;
            showQuestion();
        });

        document.getElementById('startPracticeBtn').addEventListener('click', function () {
            document.getElementById('startQuizBtn').style.display = 'none'; // Hide the button
            document.getElementById('startPracticeBtn').style.display = 'none'; // Hide the button
            document.getElementById('highscoresBtn').style.display = 'none'; // Hide the button
            document.getElementById('backBtn').style.display = 'block'; // Display time
            document.getElementById('welcomeBtn').style.display = 'none'; // Display time

            showQuestion(); // Show the first question
        });

        // započni mjeriti vrijeme
        function startQuestionTimer() {
            let timeLeft = questionTimeout / 1000;

            questionTimer = setInterval(function () {
                // Prikaz preostalog vremena
                timerDisplay.textContent = ` ${formatTime(timeLeft)}`;

                // Promjena boje ovisno o tome koliko je vremena preostalo
                changeColorBasedOnTime(timeLeft);

                // Ako je timer došao do 0 onda pređi na iduće pitanje ili submitaj formu
                if (timeLeft <= 0.1) {
                    clearInterval(questionTimer); // Zaustavi timer
                    // Iduće pitanje
                    questionContainers[currentQuestion].style.display = 'none';
                    currentQuestion++;

                    if (currentQuestion < questionContainers.length) { // ako nije zadnje pitanje
                        showQuestion();
                    } else { // ako je zadnje pitanje
                        // ubaci skupljene odgovore u skriveno polje
                        const answersInput = document.getElementById('userAnswers');
                        answersInput.value = JSON.stringify(answeredQuestions);

                        document.getElementById('quizForm').submit();
                    }
                }

                timeLeft -= 0.1; // Umanji za 0.1s
            }, 100); // Svakih 100ms updateaj
        }

        function changeColorBasedOnTime(timeLeft) {
            const yellowThreshold = 5; // na 5s mijenjaj boju u žuto
            const redThreshold = 2; // na 2s mijenjaj boju u crveno

            if (timeLeft > yellowThreshold) {
                // Zelena
                timerDisplay.style.color = '#28a745';
            } else if (timeLeft > redThreshold) {
                // Žuta
                timerDisplay.style.color = '#ffc107';
            } else {
                // Crvena
                timerDisplay.style.color = '#dc3545';
            }
        }


        function formatTime(seconds) {
            // Formatiranje sekundi
            const remainingSeconds = seconds % 60;

            return `${remainingSeconds.toFixed(1)}`;
        }

        // Adjust font size based on text length
        function adjustFontSize(container) {
            const config = getFontSizeConfig();
            const questionText = container.querySelector('.card-title');
            const answerButtons = container.querySelectorAll('.answer-button');

            // Adjust question font size
            adjustTextFontSize(questionText, config);

            // Adjust each answer button font size
            answerButtons.forEach(button => {
                adjustTextFontSize(button, config);
            });
        }

        // Adjust text font size based on its length
        function adjustTextFontSize(element, config) {
            let fontSize = config.maxFontSize;

            if (element.textContent.length > config.maxLength) {
                fontSize = config.maxFontSize - ((element.textContent.length - config.maxLength) / 50);
                if (fontSize < config.minFontSize) {
                    fontSize = config.minFontSize;
                }
            }

            element.style.fontSize = `${fontSize}rem`;
        }

        document.querySelectorAll('.answer-button').forEach(function (button) {
            button.addEventListener('click', function () {
                // Spremi kliknuti odgovor korisnika
                const questionId = questionContainers[currentQuestion].id.replace('question', '');
                answeredQuestions[questionId] = button.getAttribute('data-answer');

                // Zaustavi timer
                clearInterval(questionTimer);

                // Sakrij trenutno pitanje
                questionContainers[currentQuestion].style.display = 'none';

                // Prebaci se na iduće pitanje
                currentQuestion++;

                // Prikaži iduće pitanje ili submitaj formu ako je bilo zadnje pitanje
                if (currentQuestion < questionContainers.length) {
                    showQuestion();
                } else {
                    // ubaci skupljene odgovore u skriveno polje
                    const answersInput = document.getElementById('userAnswers');
                    answersInput.value = JSON.stringify(answeredQuestions);

                    document.getElementById('quizForm').submit();
                }
            });
        });
    });





</script>
</body>
</html>

templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FirefighterQuiz</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles-welcome.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"  />

</head>
<body>
{% include 'navbar.html' %}

<div class="container container-welcome text-center col-lg-6 col-md-8 col-11">
    <h3 class="welcome-text text-dark">Želiš li biti vatrogasac, <span style="color: #dc3545;">{{ current_user.first_name|capitalize }}</span>?</h3>
    <div class="quiz-links mt-3 mx-auto">
        {% for quiz in quizzes %}
            <a href="{{ url_for('views.quiz', quiz_id=quiz.id) }}" class="quiz-block">
                <div class="quiz-link">{{ quiz.quiz_name }}</div>
            </a>
        {% endfor %}
    </div>
</div>

{% include 'footer.html' %}


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>